---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: data-mcg
spec:
  description: data-mcg-example
  sourceRepos:
    - '{{ $.Values.helmRepoUrl }}'
  destinations:
{{- range $ns := $.Values.namespaces }}
    - namespace: {{ $ns }}
      server: https://kubernetes.default.svc
{{- end }} 
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
