{{- range $key, $val := $.Values.apps }}
{{- if $val.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $key }}
spec:
  destination:
    name: ''
    namespace: openshift-storage
    server: 'https://kubernetes.default.svc'
  source:
    path: '{{ $val.path }}'
    repoURL: '{{ $.Values.helmRepoUrl }}'
    targetRevision: '{{ $val.branch }}'
  project: data-mcg
{{- if $val.autosync }}
  syncPolicy:
    automated:
      prune: false
      selfHeal: false  
{{- end }}
{{- end }}
{{- end }}
